# Generated by Django 6.0.4 on 2026-06-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
