# Generated by Django 6.0.4 on 2026-07-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_delete_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
