# Generated by Django 6.0.4 on 2026-04-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Confirmed', 'confirmed'), ('In_progress', 'In progress'), ('Cancelled', 'cancelled')], default='Pending', max_length=200),
        ),
    ]
