# Generated by Django 6.0.4 on 2026-05-06 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_vehicle_customer'),
        ('services', '0002_alter_servicebooking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='user',
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
            preserve_default=False,
        ),
    ]
