# Generated by Django 6.0.4 on 2026-05-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_servicebooking_user_servicebooking_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Assigned', 'assigned'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('In_progress', 'In progress'), ('Completed', 'Completed'), ('Cancelled', 'cancelled')], default='Pending', max_length=200),
        ),
    ]
