# Generated by Django 6.0.4 on 2026-05-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_servicebooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='labour_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
