# Generated by Django 6.0.4 on 2026-05-16 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0011_active_mechanic_is_work_approve_and_more'),
        ('services', '0005_servicebooking_labour_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mechanic.mechanic'),
        ),
    ]
