# Generated by Django 6.0.4 on 2026-05-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0013_mechanic_aadhaar'),
        ('services', '0006_alter_servicebooking_mechanic'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='rejected_mechanics',
            field=models.ManyToManyField(blank=True, related_name='rejected_bookings', to='mechanic.mechanic'),
        ),
    ]
