# Generated by Django 6.0.4 on 2026-05-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_servicebooking_rejected_mechanics'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='location',
            field=models.TextField(default=4),
            preserve_default=False,
        ),
    ]
