# Generated by Django 6.0.4 on 2026-05-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_bill_bookingsparepart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('In_progress', 'In_progress'), ('Rejected', 'Rejected'), ('Expired', 'Expired')], default='Pending', max_length=20),
        ),
    ]
