# Generated by Django 6.0.4 on 2026-05-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_mechanicrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('In_progress', 'In_progress'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Expired', 'Expired')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='problem_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
