# Generated by Django 6.0.4 on 2026-05-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_mechanicrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='problem_description',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
    ]
