# Generated by Django 6.0.4 on 2026-05-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_servicebooking_problem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='cancelled_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
