# Generated by Django 6.0.4 on 2026-05-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_servicebooking_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
