# Generated by Django 6.0.4 on 2026-05-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_bill_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='basic_sevice_price',
            new_name='basic_service_price',
        ),
    ]
