# Generated by Django 6.0.4 on 2026-06-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
