# Generated by Django 6.0.4 on 2026-06-10 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.servicebooking'),
        ),
    ]
