# Generated by Django 6.0.4 on 2026-06-20 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_complaintchat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComplaintChat',
        ),
    ]
