# Generated by Django 6.0.4 on 2026-06-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_complaintsession_complaintchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintsession',
            name='admin_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaintsession',
            name='customer_online',
            field=models.BooleanField(default=False),
        ),
    ]
