# Generated by Django 6.0.4 on 2026-06-20 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_complaintsession_admin_online_and_more'),
        ('superuser', '0003_superadmin_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintchat',
            name='sender',
        ),
        migrations.AddField(
            model_name='complaintchat',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superuser.superadmin'),
        ),
        migrations.AddField(
            model_name='complaintchat',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
