# Generated by Django 6.0.4 on 2026-06-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_remove_complaintchat_sender_complaintchat_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintsession',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='complaintsession',
            name='closed_by',
        ),
        migrations.RemoveField(
            model_name='complaintsession',
            name='customer',
        ),
        migrations.DeleteModel(
            name='ComplaintChat',
        ),
        migrations.DeleteModel(
            name='ComplaintSession',
        ),
    ]
