# Generated by Django 6.0.4 on 2026-07-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('customer', 'Customer'), ('superuser', 'Support'), ('system', 'System')], max_length=20),
        ),
    ]
