# Generated by Django 6.0.4 on 2026-07-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('customer', 'Customer'), ('superuser', 'Superuser')], max_length=20),
        ),
    ]
