# Generated by Django 6.0.4 on 2026-07-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='customer',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
