# Generated by Django 6.0.4 on 2026-05-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='superuser_profile_pic/'),
        ),
    ]
