# Generated by Django 6.0.4 on 2026-05-16 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_profile_pic'),
        ('superuser', '0002_superadmin_address_superadmin_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.city'),
        ),
    ]
