from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_superuser, name='login_superuser'),
    path('home/', views.home_page_superuser, name='home_page_superuser'),
    path('mechanic-applications/', views.all_mechanic_applications, name='all_mechanic_applications'),
    path('application/<int:id>/', views.mechanic_application, name='mechanic_application'),
    path('approve-mechanic/<int:id>/', views.approve_mechanic, name='approve_mechanic'),
    path('reject-mechanic/<int:id>/', views.reject_mechanic, name='reject_mechanic'),
    path('customers-list/', views.all_customer_detail, name='all_customer_detail'),
    path('customer/<int:id>/', views.customer_detail, name='customer_detail'),
    path('customer/<int:customer_id>/service-order/<int:service_id>/', views.customer_details_service_order, name='customer_details_service_order'),
    path('mechanics-list/', views.all_mechanic_details, name='all_mechanic_details'),
    path('mechanic/<int:id>/', views.mechanic_deatail, name='mechanic_deatail'),
    path('mechanic/<int:mechanic_id>/service-order/<int:service_id>/', views.mechanic_details_service_order, name='mechanic_details_service_order'),
    path('rejected-mechanic/', views.rejected_mechanics, name='rejected_mechanics'),
    path('rejected-mechanic/<int:id>/', views.view_rejected_mechanic, name='view_rejected_mechanic'),
    path('logout/', views.logout_view_superuser, name='logout_view_superuser'),
    path('profile/', views.profile_page_superuser, name='profile_page_superuser'),
    path('edit-profile/<int:id>/', views.profile_page_edit_superuser, name='edit_profile_superuser'),
    path('change-password/', views.profile_superuser_change_password, name='profile_superuser_change_password'),
    path('avalable-mechanic/', views.available_mechanic, name='available_mechanic'),
    path('online-mechanic/', views.available_online, name='available_online'),
    path('complaints/', views.complaint_list_view, name='complaint_list_view'),
    path('add-complaint/', views.add_complaints, name='add_complaints'),
    path('delete-complaint/<int:id>', views.delete_complaints, name='delete_complaints'),
    path('modify-complaint/<int:id>/', views.modify_complaints, name='modify_complaints'),
    path('suspend/<int:id>/', views.suspend_mechanic, name='suspend_mechanic'),
    path('service-not-assign/', views.service_not_assign, name='service_not_assign'),
    path('service-not-assign/<int:id>/', views.service_not_assign_view, name='service_not_assign_view'),
    path('active-service/', views.active_service_booking, name='active_service_booking'),
    path('active-service/<int:id>/', views.active_service_booking_view, name='active_service_booking_view'),
    
]