# Generated by Django 6.0.4 on 2026-04-27 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_name', models.CharField(verbose_name=255)),
                ('basic_sevice_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=15)),
                ('certificate', models.FileField(upload_to='mechanic_certificate/')),
                ('experience_certificate', models.FileField(blank=True, null=True, upload_to='mechanic_experience_certificate')),
                ('password', models.CharField(max_length=20)),
                ('valid', models.BooleanField()),
                ('application_created_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.city')),
            ],
        ),
        migrations.CreateModel(
            name='Active_mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField()),
                ('available', models.BooleanField()),
                ('mechanic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mechanic.mechanic')),
            ],
        ),
        migrations.CreateModel(
            name='StockManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanic.mechanic')),
            ],
        ),
    ]
