# Generated by Django 6.0.4 on 2026-04-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaints',
        ),
    ]
