# Generated by Django 6.0.4 on 2026-04-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0002_delete_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='experience_certificate',
            field=models.FileField(blank=True, null=True, upload_to='mechanic_experience_certificate/'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
