# Generated by Django 6.0.4 on 2026-04-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0003_alter_mechanic_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
