# Generated by Django 6.0.4 on 2026-05-09 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0004_alter_mechanic_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='active_mechanic',
            old_name='available',
            new_name='is_available',
        ),
        migrations.RenameField(
            model_name='active_mechanic',
            old_name='online',
            new_name='is_online',
        ),
        migrations.RenameField(
            model_name='mechanic',
            old_name='valid',
            new_name='is_valid',
        ),
        migrations.AddField(
            model_name='stockmanagement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
