# Generated by Django 6.0.4 on 2026-05-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0005_rename_available_active_mechanic_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='mechanic_profile_pic/'),
        ),
    ]
