# Generated by Django 6.0.4 on 2026-05-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0006_mechanic_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
