# Generated by Django 6.0.4 on 2026-05-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0007_mechanic_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='is_reject',
            field=models.BooleanField(default=False),
        ),
    ]
