# Generated by Django 6.0.4 on 2026-05-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0008_mechanic_is_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='last_login_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
