# Generated by Django 6.0.4 on 2026-05-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0009_mechanic_last_login_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmanagement',
            name='stock_pic',
            field=models.ImageField(blank=True, null=True, upload_to='stock_pic/'),
        ),
    ]
