# Generated by Django 6.0.4 on 2026-05-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0010_stockmanagement_stock_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_mechanic',
            name='is_work_approve',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='active_mechanic',
            name='is_work_reject',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
