# Generated by Django 6.0.4 on 2026-05-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0011_active_mechanic_is_work_approve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_mechanic',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='active_mechanic',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
