# Generated by Django 6.0.4 on 2026-05-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0012_alter_active_mechanic_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='aadhaar',
            field=models.TextField(default=2, max_length=12),
            preserve_default=False,
        ),
    ]
