# Generated by Django 6.0.4 on 2026-05-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0013_mechanic_aadhaar'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='account_suspend',
            field=models.BooleanField(default=False),
        ),
    ]
