# Generated by Django 6.0.4 on 2026-07-07 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_account', '0001_initial'),
        ('mechanic', '0014_mechanic_account_suspend'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicPasswordOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanic.mechanic')),
            ],
        ),
    ]
