# Generated by Django 6.0.4 on 2026-07-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_account', '0002_mechanicpasswordotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_customer', models.EmailField(max_length=254)),
                ('email_mechanic', models.EmailField(max_length=254)),
                ('number_customer', models.CharField(max_length=15)),
                ('number_mechanic', models.CharField(max_length=15)),
                ('location', models.CharField()),
                ('address', models.CharField()),
            ],
        ),
    ]
