# Generated by Django 6.0.4 on 2026-07-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_account', '0003_fixigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixigo',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
