# Generated by Django 6.0.4 on 2026-07-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_account', '0004_alter_fixigo_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixigo',
            name='address',
            field=models.TextField(),
        ),
    ]
