# Generated by Django 6.0.4 on 2026-07-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_account', '0005_alter_fixigo_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
